# Generated by Django 6.0.6 on 2026-07-12 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorro',
            name='idbingo',
            field=models.ForeignKey(blank=True, db_column='idbingo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.bingo', verbose_name='Bingo Asociado'),
        ),
    ]
