# Generated by Django 6.0.6 on 2026-07-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_alter_ahorro_idbingo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aportesemanal',
            name='chk_aportesemanal_metodoingreso',
        ),
        migrations.AddField(
            model_name='aportesemanal',
            name='origenahorro',
            field=models.CharField(blank=True, default='Directo', max_length=50, null=True, verbose_name='Origen del Ahorro'),
        ),
        migrations.AddConstraint(
            model_name='aportesemanal',
            constraint=models.CheckConstraint(condition=models.Q(('metodoingreso__in', ['Efectivo', 'Transferencia', 'Fisico']), ('metodoingreso__isnull', True), _connector='OR'), name='chk_aportesemanal_metodoingreso'),
        ),
    ]
