# Generated by Django 6.0.6 on 2026-07-05 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_aportesemanal_montoaporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobanteahorro',
            field=models.FileField(blank=True, null=True, upload_to='ahorro/comprobantes/', verbose_name='Comprobante de Ahorro'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='idmetodopago',
            field=models.ForeignKey(blank=True, db_column='idmetodopago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.metodopago', verbose_name='Cuenta de Destino'),
        ),
    ]
