# Generated by Django 6.0.6 on 2026-07-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_remove_aportesemanal_chk_aportesemanal_metodoingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aportesemanal',
            name='origenahorro',
        ),
        migrations.AddField(
            model_name='ahorro',
            name='origenahorro',
            field=models.CharField(blank=True, default='Directo', max_length=50, null=True, verbose_name='Origen del Ahorro'),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='estadoahorro',
            field=models.CharField(choices=[('Acreditado', 'Acreditado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=25, verbose_name='Estado del Ahorro'),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='montoahorro',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Ahorrado'),
        ),
    ]
