# Generated by Django 6.0.6 on 2026-07-05 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_pago_comprobanteahorro_alter_pago_idmetodopago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='comprobanteahorro',
        ),
        migrations.AddField(
            model_name='ahorro',
            name='comprobanteahorro',
            field=models.FileField(blank=True, null=True, upload_to='ahorro/comprobantes/', verbose_name='Comprobante de Ahorro'),
        ),
        migrations.AddField(
            model_name='ahorro',
            name='idmetodopago',
            field=models.ForeignKey(blank=True, db_column='idmetodopago', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.metodopago', verbose_name='Cuenta de Destino'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='idmetodopago',
            field=models.ForeignKey(db_column='idmetodopago', default=1, on_delete=django.db.models.deletion.PROTECT, to='bingo.metodopago', verbose_name='Método de Pago'),
            preserve_default=False,
        ),
    ]
